### ISSUE TITLE
Нет ни одного ишью.

### ISSUE THREAD

**Issue by unjeru** [AlexseyKh/InformationSystem#10]
А столько работы сделано.
Каждый должен завести себе хотя бы две иши на свои ближайшие +- атомарные работы.
По окончанию отписаться сюда.

**Comment by AlexseyKh** [comment]
добавил задачи https://github.com/AlexseyKh/InformationSystem/issues/11

**Comment by PilgininIgor** [comment]
завел ишью, содержащую возможности модели-контролера #14
